// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// DeleteItemNoContent is response for DeleteItem operation.
type DeleteItemNoContent struct{}

func (*DeleteItemNoContent) deleteItemRes() {}

// DeleteItemNotFound is response for DeleteItem operation.
type DeleteItemNotFound struct{}

func (*DeleteItemNotFound) deleteItemRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) createItemRes()            {}
func (*ErrorResponse) createSubjectRelationRes() {}
func (*ErrorResponse) createSubjectRes()         {}
func (*ErrorResponse) updateItemRes()            {}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// GetItemNotFound is response for GetItem operation.
type GetItemNotFound struct{}

func (*GetItemNotFound) getItemRes() {}

// GetSubjectNotFound is response for GetSubject operation.
type GetSubjectNotFound struct{}

func (*GetSubjectNotFound) getSubjectRes() {}

// Ref: #/components/schemas/Item
type Item struct {
	ID        int64     `json:"id"`
	UUID      uuid.UUID `json:"uuid"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	Price     float32   `json:"price"`
}

// GetID returns the value of ID.
func (s *Item) GetID() int64 {
	return s.ID
}

// GetUUID returns the value of UUID.
func (s *Item) GetUUID() uuid.UUID {
	return s.UUID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Item) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetName returns the value of Name.
func (s *Item) GetName() string {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *Item) GetPrice() float32 {
	return s.Price
}

// SetID sets the value of ID.
func (s *Item) SetID(val int64) {
	s.ID = val
}

// SetUUID sets the value of UUID.
func (s *Item) SetUUID(val uuid.UUID) {
	s.UUID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Item) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetName sets the value of Name.
func (s *Item) SetName(val string) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *Item) SetPrice(val float32) {
	s.Price = val
}

// Ref: #/components/schemas/ItemCreateRequest
type ItemCreateRequest struct {
	Data ItemIn `json:"data"`
}

// GetData returns the value of Data.
func (s *ItemCreateRequest) GetData() ItemIn {
	return s.Data
}

// SetData sets the value of Data.
func (s *ItemCreateRequest) SetData(val ItemIn) {
	s.Data = val
}

// Ref: #/components/schemas/ItemCreateResponse
type ItemCreateResponse struct {
	Data Item     `json:"data"`
	Meta ItemMeta `json:"meta"`
}

// GetData returns the value of Data.
func (s *ItemCreateResponse) GetData() Item {
	return s.Data
}

// GetMeta returns the value of Meta.
func (s *ItemCreateResponse) GetMeta() ItemMeta {
	return s.Meta
}

// SetData sets the value of Data.
func (s *ItemCreateResponse) SetData(val Item) {
	s.Data = val
}

// SetMeta sets the value of Meta.
func (s *ItemCreateResponse) SetMeta(val ItemMeta) {
	s.Meta = val
}

func (*ItemCreateResponse) createItemRes() {}

// Ref: #/components/schemas/ItemGetResponse
type ItemGetResponse struct {
	Data Item     `json:"data"`
	Meta ItemMeta `json:"meta"`
}

// GetData returns the value of Data.
func (s *ItemGetResponse) GetData() Item {
	return s.Data
}

// GetMeta returns the value of Meta.
func (s *ItemGetResponse) GetMeta() ItemMeta {
	return s.Meta
}

// SetData sets the value of Data.
func (s *ItemGetResponse) SetData(val Item) {
	s.Data = val
}

// SetMeta sets the value of Meta.
func (s *ItemGetResponse) SetMeta(val ItemMeta) {
	s.Meta = val
}

func (*ItemGetResponse) getItemRes() {}

// Ref: #/components/schemas/ItemIn
type ItemIn struct {
	Name  string  `json:"name"`
	Price float32 `json:"price"`
}

// GetName returns the value of Name.
func (s *ItemIn) GetName() string {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *ItemIn) GetPrice() float32 {
	return s.Price
}

// SetName sets the value of Name.
func (s *ItemIn) SetName(val string) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *ItemIn) SetPrice(val float32) {
	s.Price = val
}

// Ref: #/components/schemas/ItemMeta
type ItemMeta struct {
	ItemStatus OptItemMetaItemStatus `json:"item_status"`
}

// GetItemStatus returns the value of ItemStatus.
func (s *ItemMeta) GetItemStatus() OptItemMetaItemStatus {
	return s.ItemStatus
}

// SetItemStatus sets the value of ItemStatus.
func (s *ItemMeta) SetItemStatus(val OptItemMetaItemStatus) {
	s.ItemStatus = val
}

type ItemMetaItemStatus string

const (
	ItemMetaItemStatusCreated ItemMetaItemStatus = "created"
	ItemMetaItemStatusFetched ItemMetaItemStatus = "fetched"
	ItemMetaItemStatusUpdated ItemMetaItemStatus = "updated"
	ItemMetaItemStatusDeleted ItemMetaItemStatus = "deleted"
)

// AllValues returns all ItemMetaItemStatus values.
func (ItemMetaItemStatus) AllValues() []ItemMetaItemStatus {
	return []ItemMetaItemStatus{
		ItemMetaItemStatusCreated,
		ItemMetaItemStatusFetched,
		ItemMetaItemStatusUpdated,
		ItemMetaItemStatusDeleted,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ItemMetaItemStatus) MarshalText() ([]byte, error) {
	switch s {
	case ItemMetaItemStatusCreated:
		return []byte(s), nil
	case ItemMetaItemStatusFetched:
		return []byte(s), nil
	case ItemMetaItemStatusUpdated:
		return []byte(s), nil
	case ItemMetaItemStatusDeleted:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ItemMetaItemStatus) UnmarshalText(data []byte) error {
	switch ItemMetaItemStatus(data) {
	case ItemMetaItemStatusCreated:
		*s = ItemMetaItemStatusCreated
		return nil
	case ItemMetaItemStatusFetched:
		*s = ItemMetaItemStatusFetched
		return nil
	case ItemMetaItemStatusUpdated:
		*s = ItemMetaItemStatusUpdated
		return nil
	case ItemMetaItemStatusDeleted:
		*s = ItemMetaItemStatusDeleted
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ItemUpdateRequest
type ItemUpdateRequest struct {
	Data ItemIn `json:"data"`
}

// GetData returns the value of Data.
func (s *ItemUpdateRequest) GetData() ItemIn {
	return s.Data
}

// SetData sets the value of Data.
func (s *ItemUpdateRequest) SetData(val ItemIn) {
	s.Data = val
}

// Ref: #/components/schemas/ItemUpdateResponse
type ItemUpdateResponse struct {
	Data Item     `json:"data"`
	Meta ItemMeta `json:"meta"`
}

// GetData returns the value of Data.
func (s *ItemUpdateResponse) GetData() Item {
	return s.Data
}

// GetMeta returns the value of Meta.
func (s *ItemUpdateResponse) GetMeta() ItemMeta {
	return s.Meta
}

// SetData sets the value of Data.
func (s *ItemUpdateResponse) SetData(val Item) {
	s.Data = val
}

// SetMeta sets the value of Meta.
func (s *ItemUpdateResponse) SetMeta(val ItemMeta) {
	s.Meta = val
}

func (*ItemUpdateResponse) updateItemRes() {}

// NewOptItemMetaItemStatus returns new OptItemMetaItemStatus with value set to v.
func NewOptItemMetaItemStatus(v ItemMetaItemStatus) OptItemMetaItemStatus {
	return OptItemMetaItemStatus{
		Value: v,
		Set:   true,
	}
}

// OptItemMetaItemStatus is optional ItemMetaItemStatus.
type OptItemMetaItemStatus struct {
	Value ItemMetaItemStatus
	Set   bool
}

// IsSet returns true if OptItemMetaItemStatus was set.
func (o OptItemMetaItemStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptItemMetaItemStatus) Reset() {
	var v ItemMetaItemStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptItemMetaItemStatus) SetTo(v ItemMetaItemStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptItemMetaItemStatus) Get() (v ItemMetaItemStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptItemMetaItemStatus) Or(d ItemMetaItemStatus) ItemMetaItemStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PingResponse
type PingResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingResponse) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/Subject
type Subject struct {
	ID        int64     `json:"id"`
	UUID      uuid.UUID `json:"uuid"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
}

// GetID returns the value of ID.
func (s *Subject) GetID() int64 {
	return s.ID
}

// GetUUID returns the value of UUID.
func (s *Subject) GetUUID() uuid.UUID {
	return s.UUID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Subject) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetName returns the value of Name.
func (s *Subject) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Subject) SetID(val int64) {
	s.ID = val
}

// SetUUID sets the value of UUID.
func (s *Subject) SetUUID(val uuid.UUID) {
	s.UUID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Subject) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetName sets the value of Name.
func (s *Subject) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/SubjectCreateRequest
type SubjectCreateRequest struct {
	Data SubjectIn `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectCreateRequest) GetData() SubjectIn {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectCreateRequest) SetData(val SubjectIn) {
	s.Data = val
}

// Ref: #/components/schemas/SubjectCreateResponse
type SubjectCreateResponse struct {
	Data Subject `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectCreateResponse) GetData() Subject {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectCreateResponse) SetData(val Subject) {
	s.Data = val
}

func (*SubjectCreateResponse) createSubjectRes() {}

// Ref: #/components/schemas/SubjectGetResponse
type SubjectGetResponse struct {
	Data Subject `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectGetResponse) GetData() Subject {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectGetResponse) SetData(val Subject) {
	s.Data = val
}

func (*SubjectGetResponse) getSubjectRes() {}

// Ref: #/components/schemas/SubjectIn
type SubjectIn struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *SubjectIn) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *SubjectIn) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/SubjectRelation
type SubjectRelation struct {
	ID               int64     `json:"id"`
	CreatedAt        time.Time `json:"created_at"`
	SubjectID        int64     `json:"subject_id"`
	RelatedSubjectID int64     `json:"related_subject_id"`
}

// GetID returns the value of ID.
func (s *SubjectRelation) GetID() int64 {
	return s.ID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SubjectRelation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetSubjectID returns the value of SubjectID.
func (s *SubjectRelation) GetSubjectID() int64 {
	return s.SubjectID
}

// GetRelatedSubjectID returns the value of RelatedSubjectID.
func (s *SubjectRelation) GetRelatedSubjectID() int64 {
	return s.RelatedSubjectID
}

// SetID sets the value of ID.
func (s *SubjectRelation) SetID(val int64) {
	s.ID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SubjectRelation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetSubjectID sets the value of SubjectID.
func (s *SubjectRelation) SetSubjectID(val int64) {
	s.SubjectID = val
}

// SetRelatedSubjectID sets the value of RelatedSubjectID.
func (s *SubjectRelation) SetRelatedSubjectID(val int64) {
	s.RelatedSubjectID = val
}

// Ref: #/components/schemas/SubjectRelationCreateRequest
type SubjectRelationCreateRequest struct {
	Data SubjectRelationIn `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectRelationCreateRequest) GetData() SubjectRelationIn {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectRelationCreateRequest) SetData(val SubjectRelationIn) {
	s.Data = val
}

// Ref: #/components/schemas/SubjectRelationCreateResponse
type SubjectRelationCreateResponse struct {
	Data SubjectRelation `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectRelationCreateResponse) GetData() SubjectRelation {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectRelationCreateResponse) SetData(val SubjectRelation) {
	s.Data = val
}

func (*SubjectRelationCreateResponse) createSubjectRelationRes() {}

// Ref: #/components/schemas/SubjectRelationIn
type SubjectRelationIn struct {
	SubjectID        int64 `json:"subject_id"`
	RelatedSubjectID int64 `json:"related_subject_id"`
}

// GetSubjectID returns the value of SubjectID.
func (s *SubjectRelationIn) GetSubjectID() int64 {
	return s.SubjectID
}

// GetRelatedSubjectID returns the value of RelatedSubjectID.
func (s *SubjectRelationIn) GetRelatedSubjectID() int64 {
	return s.RelatedSubjectID
}

// SetSubjectID sets the value of SubjectID.
func (s *SubjectRelationIn) SetSubjectID(val int64) {
	s.SubjectID = val
}

// SetRelatedSubjectID sets the value of RelatedSubjectID.
func (s *SubjectRelationIn) SetRelatedSubjectID(val int64) {
	s.RelatedSubjectID = val
}

// UpdateItemNotFound is response for UpdateItem operation.
type UpdateItemNotFound struct{}

func (*UpdateItemNotFound) updateItemRes() {}
