// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) createSubjectRelationRes() {}
func (*ErrorResponse) createSubjectRes()         {}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// GetSubjectByNameNotFound is response for GetSubjectByName operation.
type GetSubjectByNameNotFound struct{}

func (*GetSubjectByNameNotFound) getSubjectByNameRes() {}

// Ref: #/components/schemas/KgVersion
type KgVersion string

const (
	KgVersion1  KgVersion = "1"
	KgVersion2  KgVersion = "2"
	KgVersion3  KgVersion = "3"
	KgVersion4  KgVersion = "4"
	KgVersion5  KgVersion = "5"
	KgVersion6  KgVersion = "6"
	KgVersion7  KgVersion = "7"
	KgVersion8  KgVersion = "8"
	KgVersion9  KgVersion = "9"
	KgVersion10 KgVersion = "10"
)

// AllValues returns all KgVersion values.
func (KgVersion) AllValues() []KgVersion {
	return []KgVersion{
		KgVersion1,
		KgVersion2,
		KgVersion3,
		KgVersion4,
		KgVersion5,
		KgVersion6,
		KgVersion7,
		KgVersion8,
		KgVersion9,
		KgVersion10,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s KgVersion) MarshalText() ([]byte, error) {
	switch s {
	case KgVersion1:
		return []byte(s), nil
	case KgVersion2:
		return []byte(s), nil
	case KgVersion3:
		return []byte(s), nil
	case KgVersion4:
		return []byte(s), nil
	case KgVersion5:
		return []byte(s), nil
	case KgVersion6:
		return []byte(s), nil
	case KgVersion7:
		return []byte(s), nil
	case KgVersion8:
		return []byte(s), nil
	case KgVersion9:
		return []byte(s), nil
	case KgVersion10:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *KgVersion) UnmarshalText(data []byte) error {
	switch KgVersion(data) {
	case KgVersion1:
		*s = KgVersion1
		return nil
	case KgVersion2:
		*s = KgVersion2
		return nil
	case KgVersion3:
		*s = KgVersion3
		return nil
	case KgVersion4:
		*s = KgVersion4
		return nil
	case KgVersion5:
		*s = KgVersion5
		return nil
	case KgVersion6:
		*s = KgVersion6
		return nil
	case KgVersion7:
		*s = KgVersion7
		return nil
	case KgVersion8:
		*s = KgVersion8
		return nil
	case KgVersion9:
		*s = KgVersion9
		return nil
	case KgVersion10:
		*s = KgVersion10
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PingResponse
type PingResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingResponse) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/Subject
type Subject struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Subject) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Subject) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Subject) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Subject) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/SubjectCreateRequest
type SubjectCreateRequest struct {
	Data      SubjectIn `json:"data"`
	KgVersion KgVersion `json:"kg_version"`
}

// GetData returns the value of Data.
func (s *SubjectCreateRequest) GetData() SubjectIn {
	return s.Data
}

// GetKgVersion returns the value of KgVersion.
func (s *SubjectCreateRequest) GetKgVersion() KgVersion {
	return s.KgVersion
}

// SetData sets the value of Data.
func (s *SubjectCreateRequest) SetData(val SubjectIn) {
	s.Data = val
}

// SetKgVersion sets the value of KgVersion.
func (s *SubjectCreateRequest) SetKgVersion(val KgVersion) {
	s.KgVersion = val
}

// Ref: #/components/schemas/SubjectCreateResponse
type SubjectCreateResponse struct {
	Data Subject `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectCreateResponse) GetData() Subject {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectCreateResponse) SetData(val Subject) {
	s.Data = val
}

func (*SubjectCreateResponse) createSubjectRes() {}

// Ref: #/components/schemas/SubjectGetResponse
type SubjectGetResponse struct {
	Data Subject `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectGetResponse) GetData() Subject {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectGetResponse) SetData(val Subject) {
	s.Data = val
}

func (*SubjectGetResponse) getSubjectByNameRes() {}

// Ref: #/components/schemas/SubjectIn
type SubjectIn struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *SubjectIn) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *SubjectIn) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/SubjectRelation
type SubjectRelation struct {
	SubjectID        string `json:"subject_id"`
	RelatedSubjectID string `json:"related_subject_id"`
}

// GetSubjectID returns the value of SubjectID.
func (s *SubjectRelation) GetSubjectID() string {
	return s.SubjectID
}

// GetRelatedSubjectID returns the value of RelatedSubjectID.
func (s *SubjectRelation) GetRelatedSubjectID() string {
	return s.RelatedSubjectID
}

// SetSubjectID sets the value of SubjectID.
func (s *SubjectRelation) SetSubjectID(val string) {
	s.SubjectID = val
}

// SetRelatedSubjectID sets the value of RelatedSubjectID.
func (s *SubjectRelation) SetRelatedSubjectID(val string) {
	s.RelatedSubjectID = val
}

// Ref: #/components/schemas/SubjectRelationCreateRequest
type SubjectRelationCreateRequest struct {
	Data      SubjectRelationIn `json:"data"`
	KgVersion KgVersion         `json:"kg_version"`
}

// GetData returns the value of Data.
func (s *SubjectRelationCreateRequest) GetData() SubjectRelationIn {
	return s.Data
}

// GetKgVersion returns the value of KgVersion.
func (s *SubjectRelationCreateRequest) GetKgVersion() KgVersion {
	return s.KgVersion
}

// SetData sets the value of Data.
func (s *SubjectRelationCreateRequest) SetData(val SubjectRelationIn) {
	s.Data = val
}

// SetKgVersion sets the value of KgVersion.
func (s *SubjectRelationCreateRequest) SetKgVersion(val KgVersion) {
	s.KgVersion = val
}

// Ref: #/components/schemas/SubjectRelationCreateResponse
type SubjectRelationCreateResponse struct {
	Data SubjectRelation `json:"data"`
}

// GetData returns the value of Data.
func (s *SubjectRelationCreateResponse) GetData() SubjectRelation {
	return s.Data
}

// SetData sets the value of Data.
func (s *SubjectRelationCreateResponse) SetData(val SubjectRelation) {
	s.Data = val
}

func (*SubjectRelationCreateResponse) createSubjectRelationRes() {}

// Ref: #/components/schemas/SubjectRelationIn
type SubjectRelationIn struct {
	SubjectID        string `json:"subject_id"`
	RelatedSubjectID string `json:"related_subject_id"`
}

// GetSubjectID returns the value of SubjectID.
func (s *SubjectRelationIn) GetSubjectID() string {
	return s.SubjectID
}

// GetRelatedSubjectID returns the value of RelatedSubjectID.
func (s *SubjectRelationIn) GetRelatedSubjectID() string {
	return s.RelatedSubjectID
}

// SetSubjectID sets the value of SubjectID.
func (s *SubjectRelationIn) SetSubjectID(val string) {
	s.SubjectID = val
}

// SetRelatedSubjectID sets the value of RelatedSubjectID.
func (s *SubjectRelationIn) SetRelatedSubjectID(val string) {
	s.RelatedSubjectID = val
}

// TruncateTablesOK is response for TruncateTables operation.
type TruncateTablesOK struct{}
