// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateSubjectRelationRes interface {
	createSubjectRelationRes()
}

type CreateSubjectRes interface {
	createSubjectRes()
}

type GetSubjectByNameRes interface {
	getSubjectByNameRes()
}
