// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateItemRes interface {
	createItemRes()
}

type CreateSubjectRelationRes interface {
	createSubjectRelationRes()
}

type CreateSubjectRes interface {
	createSubjectRes()
}

type DeleteItemRes interface {
	deleteItemRes()
}

type GetItemRes interface {
	getItemRes()
}

type GetSubjectRes interface {
	getSubjectRes()
}

type UpdateItemRes interface {
	updateItemRes()
}
