// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateSubject implements createSubject operation.
	//
	// Creates Subject.
	//
	// POST /subjects
	CreateSubject(ctx context.Context, req *SubjectCreateRequest) (CreateSubjectRes, error)
	// CreateSubjectRelation implements createSubjectRelation operation.
	//
	// Creates Subject Relation.
	//
	// POST /subject_relations
	CreateSubjectRelation(ctx context.Context, req *SubjectRelationCreateRequest) (CreateSubjectRelationRes, error)
	// GetSubject implements getSubject operation.
	//
	// Returns a single Subject by id.
	//
	// GET /subjects/{subjectId}
	GetSubject(ctx context.Context, params GetSubjectParams) (GetSubjectRes, error)
	// Ping implements ping operation.
	//
	// Check if the service is running.
	//
	// GET /ping
	Ping(ctx context.Context) (*PingResponse, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
