// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateSubjectOperation         OperationName = "CreateSubject"
	CreateSubjectRelationOperation OperationName = "CreateSubjectRelation"
	GetSubjectOperation            OperationName = "GetSubject"
	GetSubjectByNameOperation      OperationName = "GetSubjectByName"
	PingOperation                  OperationName = "Ping"
)
