// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateItemOperation            OperationName = "CreateItem"
	CreateSubjectOperation         OperationName = "CreateSubject"
	CreateSubjectRelationOperation OperationName = "CreateSubjectRelation"
	DeleteItemOperation            OperationName = "DeleteItem"
	GetItemOperation               OperationName = "GetItem"
	GetSubjectOperation            OperationName = "GetSubject"
	PingOperation                  OperationName = "Ping"
	UpdateItemOperation            OperationName = "UpdateItem"
)
