// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateSubject implements createSubject operation.
//
// Creates Subject.
//
// POST /subjects
func (UnimplementedHandler) CreateSubject(ctx context.Context, req *SubjectCreateRequest) (r CreateSubjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSubjectRelation implements createSubjectRelation operation.
//
// Creates Subject Relation.
//
// POST /subject-relations
func (UnimplementedHandler) CreateSubjectRelation(ctx context.Context, req *SubjectRelationCreateRequest) (r CreateSubjectRelationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubject implements getSubject operation.
//
// Returns a single Subject by id.
//
// GET /subjects/{subjectId}
func (UnimplementedHandler) GetSubject(ctx context.Context, params GetSubjectParams) (r GetSubjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubjectByName implements getSubjectByName operation.
//
// Returns subject by name.
//
// GET /subjects
func (UnimplementedHandler) GetSubjectByName(ctx context.Context, params GetSubjectByNameParams) (r GetSubjectByNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// Check if the service is running.
//
// GET /ping
func (UnimplementedHandler) Ping(ctx context.Context) (r *PingResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
